version: '3'
services:
  nani:
    image: banalanaveenkumar/doc.jenkins.venkyrepo:latest
    ports:
      - "90:80"
  deploy: 3
  replicas: 3
 nekki:
    image: banalanaveenkumar/doc.jenkins.venkyrepo:latest
    ports:
      - "91:80"
  deploy:
  replicas: 3
 venky:
    image: banalanaveenkumar/doc.jenkins.venkyrepo:latest
    ports:
      - "92:80"
  deploy:
  replicas: 3
